"""add new field in the model

Revision ID: 05c426f7cbd5
Revises: 3bc992eb8b80
Create Date: 2023-07-25 10:13:11.613595

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "05c426f7cbd5"
down_revision = "3bc992eb8b80"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("hashed_password", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "hashed_password")
    # ### end Alembic commands ###
