version: "3.8"
services:
  db:
    container_name: db
    restart: always
    image: postgres:12.4-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    env_file:
      .env
    expose:
      - 5432