version: "3.2"
services:
  db:
    container_name: db
    restart: always
    image: postgres:12.4-alpine
    environment:
      - POSTGRES_USER=polls_superuser
      - POSTGRES_PASSWORD=password-polls
      - POSTGRES_DB=polls_superuser
    ports:
      - "5433:5433"
    networks:
      - custom
  db_test:
    container_name: "db_test"
    restart: always
    image: postgres:12.4-alpine
    environment:
      - POSTGRES_USER=polls_test
      - POSTGRES_PASSWORD=password-test
      - POSTGRES_DB=polls_test
    ports:
      - "5434:5433"
    networks:
      - custom
networks:
  custom:
    driver: bridge
