version: "3.8"
services:
  db:
    container_name: db
    restart: always
    image: postgres:12.4-alpine
    environment:
      - POSTGRES_USER=superuser
      - POSTGRES_PASSWORD=ZAQ!@#$%tgb
      - POSTGRES_DB=all_bd
    ports:
      - "5433:5433"
    networks:
      - custom
  db_test:
    container_name: "db_test"
    restart: always
    image: postgres:12.4-alpine
    environment:
      - POSTGRES_USER=superuser_test
      - POSTGRES_PASSWORD=ZAQ!@#$%tgb
      - POSTGRES_DB=all_bd_test
    ports:
      - "5434:5433"
    networks:
      - custom
networks:
  custom:
    driver: bridge
